### PR TITLE
Bump core-foundation(-sys) to 0.7.1 for release.

### PR DESCRIPTION
**Pull request by anp**
Hi! I'm hoping to be able to pull https://github.com/servo/core-foundation-rs/pull/357 from crates.io and based on other issue threads here it seems that a PR with version bumps is the way to request a release.

I haven't used my local mac recently so I'm relying on CI for now, although if needed I can spin that up and test it locally. LMK?

I'm not actually sure whether the changes to core-foundation since 2019/11 qualify for a patch version bump or a minor one. Thoughts?

### CODE REVIEW

**Comment by jdm** [comment]
I've double checked the changes to core-foundation and core-foundation-sys and a minor version change looks good for both. Thanks!

**Comment by jdm** [comment]
Published.

**Comment by jdm** [comment]
FYI: we ended up having to do a major version bump after all and yank the new minor releases.

**Comment by anp** [comment]
Appreciate the heads up, sorry for the hassle!

**Pull request merged**
