### PR TITLE
Bump core graphics version to 0.18.0

### PR DESCRIPTION
**Pull request by zubivan**
As discussed in #339 bumping version of core graphics to the next minor.

### CODE REVIEW

**Comment by jdm** [comment]
Published.

**Comment by zubivan** [comment]
@jdm thanks!

**Comment by nox** [comment]
core-graphics is exposed in core-text's public API. This should have been a core-text breaking change. Please don't update crates without updating the others, now I have releases to yank.

**Comment by jdm** [comment]
To be clear - nothing in this PR is incorrect, because core-text's version was not updated at all. I did a major version update in #346.

**Comment by nox** [comment]
My complaint is that there was no paper trail that there were unpublished breaking changes in the tree, and thus core-text actually needed a breaking bump.

**Pull request merged**
