### PR TITLE
Upgrade to libc 0.2

### PR DESCRIPTION
**Pull request by mbrubeck**
[Review on Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/71)

### CODE REVIEW

**Comment by metajack** [comment]
This PR needs a rebase.

**Comment by mbrubeck** [comment]
Rebased and ready to merge.

**Comment by metajack** [comment]
@bors-servo r+


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/core-foundation-rs/71)

**Pull request merged**
