### PR TITLE
Add Cargo workspace config.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/100)

### CODE REVIEW

**Comment by faern** [comment]
With the addition of the workspace you can remove the `cd core-foundation` part of `.travis.yml`. The build and tests can be run from the repo root.

**Comment by frewsxcv** [comment]
looks like homu isn't setup for this repo

**Comment by faern** [comment]
@frewsxcv Maybe a rebase as well? To avoid a merge with something very far back :)

**Comment by frewsxcv** [comment]
@bots-servo retry

**Pull request merged**
