### PR TITLE
Release for core-graphics  

### PR DESCRIPTION
**Pull request by fcfangcc**
Release core-graphics  version to 0.22.4

Include #554 , I urgently need to use it. Thanks 😃

### CODE REVIEW

**Comment by jdm** [comment]
Published.

**Comment by jdm** [comment]
I had to yank the- new version. This will need to be 0.23.0 instead due to the update to foreign-types that was present in this release.

**Comment by jrmuizel** [comment]
Perhaps we should be running `cargo-semver-checks` in CI?

**Pull request merged**
