### PR TITLE
Expose the CTFont-creation functions with `options` parameter

### PR DESCRIPTION
**Pull request by jfkthame**

### CODE REVIEW

**Review by jrmuizel — APPROVED** [review]

**Comment by jrmuizel** [comment]
@jfkthame The rustfmt job is failing. Can you fix it?

**Comment by jrmuizel** [comment]
Hmm, it looks like rustfmt commit didn't make it in. (I still don't quite understand how the github merge bot works)

**Comment by jfkthame** [comment]
Yeah, I saw that. :( Maybe because it hadn't been reviewed? Not sure what the best way to clean up would be - do we need to make a new PR just for the formatting?

**Comment by jfkthame** [comment]
I don't know how to do a followup here (if it's possible at all), so I simply opened a new PR #637 for the rustfmt fix.

**Pull request merged**
