### PR TITLE
Bump core-foundation crate version

### PR DESCRIPTION
**Pull request by n-eq**
Following https://github.com/servo/core-foundation-rs/pull/477

### CODE REVIEW

**Comment by n-eq** [comment]
I'm not sure I understand the reason why Travis failed. Can someone rerun the job please (I don't have the right)? I think it didn't start correctly.

**Comment by n-eq** [comment]
Hello, can someone please review? We would like to upgrade cocoa-foundation as a dependency but my last #477 PR is not deployed yet to the crate

**Comment by n-eq** [comment]
Hello @jrmuizel , do you know why merging this PR didn't create a new release with tag 0.9.3?

**Comment by n-eq** [comment]
Hello Jeff @jrmuizel can you please release cocoa version 0.25.0? Thank you

**Comment by jrmuizel** [comment]
I'll try to remember to do this tomorrow.

**Pull request merged**
