### PR TITLE
Support converting non-utf8 paths to CFURLs

### PR DESCRIPTION
**Pull request by jrmuizel**
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/120)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Does core-foundation even exist on non-OS-X?

**Comment by jrmuizel** [comment]
Yeah, you can compile it for a variety of platforms. Windows is explicitly
supported. I don't think this crate supports that, but I didn't want to
preclude it from happening.

**Comment by SimonSapin** [comment]
Alright. Looks good!

@bors-servo r+

**Pull request merged**
