### PR TITLE
Update to 2018 edition

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This doesn't get away from `extern crate` yet.

Is this set of changes welcome?

### CODE REVIEW

**Comment by jdm** [comment]
I'm in favour.

**Comment by waywardmonkeys** [comment]
@jdm Okay, marked as ready for review and rebased.

Follow up PRs can do things like update to 2021 edition (MSRV is 1.56, so that's probably fine) and remove all of the `extern crate` stuff.

**Comment by waywardmonkeys** [comment]
@jdm Any further thoughts on this?

**Comment by jrmuizel** [comment]
I quickly skimmed it. Can you add a summary of what was changed to the commit message?

**Comment by waywardmonkeys** [comment]
@jrmuizel Done.

**Review by jrmuizel — APPROVED** [review]

**Pull request merged**
