### PR TITLE
Do not use 'links' in Cargo.toml (fixes #97)

### LINKED ISSUE #97: Stop using links
AFAIK, the `links` attribute in Cargo only exist because on some platforms, linking multiple times to a single thing is a recipe for failure. I don't think that is the case for macOS frameworks, and having Cargo fail because two core-foundation-sys versions are used in a single project is a PITA (see #96).

We should probably not use `links` if we can afford to make do without it.

Cc @tomaka for the initial paper cut, @alexcrichton for his Cargo knowledge and to confirm or infirm what I just wrote.

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/98)

### CODE REVIEW

**Comment by jdm** [comment]
If someone verifies that an application relying on core-foundation-rs still builds after this change, r=me.

**Comment by nox** [comment]
I checked with the cocoa examples.

@bors-servo r=jdm

**Comment by jrmuizel** [comment]
I think you may need to kick the ci (travis had a bad day today).

**Pull request merged**
