### PR TITLE
Modernization and cleanup

### PR DESCRIPTION
**Pull request by sfackler**
Changes are split up into a set of separate commits.

[Review on Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/69)

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good, just had a couple of nits.

**Comment by sfackler** [comment]
Updated, thanks for taking a look!

**Comment by sfackler** [comment]
There's also some breaking updates I'd like to make (e.g. making the parameter to `TCFType` into an associated type) - not sure how you want to schedule that stuff.

**Pull request merged**
