### PR TITLE
Update to use 2021 edition, and update deps

### PR DESCRIPTION
**Pull request by burtonageo**
I understand this is a big review, but I tried to change the minimal amount to get it compiling under the new circumstances.

### CODE REVIEW

**Comment by jrmuizel** [comment]
Can you separate out the dependency updates?

**Comment by jrmuizel** [comment]
Ideally each one separately

**Comment by burtonageo** [comment]
I've moved the dependency upgrade to https://github.com/servo/core-foundation-rs/pull/545, so I can probably close this PR for now

**Comment by mrobinson** [comment]
This is probably duplicated by #704 now.

**Pull request closed without merging**
