### PR TITLE
fix: Correcting errors in window CGWindowListOption values

### PR DESCRIPTION
**Pull request by nashaofu**
https://developer.apple.com/documentation/coregraphics/quartz_window_services/window_image_types?language=objc
image

### CODE REVIEW

**Review by madsmtm — APPROVED** [review]
Note that these are also defined (correctly) over in

https://github.com/servo/core-foundation-rs/blob/d4ce710182f1756c9d874ab917283fe1a1b7a011/core-graphics/src/display.rs#L33-L38

**Comment by nashaofu** [comment]
> Note that these are also defined (correctly) over in
> 
> https://github.com/servo/core-foundation-rs/blob/d4ce710182f1756c9d874ab917283fe1a1b7a011/core-graphics/src/display.rs#L33-L38

Why are there so many duplicate definitions in the project? Is there any problem if I remove it?

**Review by jdm — APPROVED** [review]
Thanks!

**Comment by jdm** [comment]
Cleaning up duplicate definitions would be great!

**Pull request merged**
