### PR TITLE
Add CFBundle::private_frameworks_url() exposing CFBundleCopyPrivateFr…

### PR DESCRIPTION
**Pull request by nikhilm**
…ameworksURL().

If this is merged, would it be possible to cut a release after?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/103)

### CODE REVIEW

**Comment by jdm** [comment]
If you update the crate's version number, it will be very easy to publish a release after.

**Comment by nikhilm** [comment]
@jdm what happened here? Did the subsequent r- pause the commit? Just wondering if I should bump the version in this PR or create a new PR. Thanks!

**Comment by jdm** [comment]
Yes, bump the version in this PR please.

**Comment by nikhilm** [comment]
Thanks Josh!

**Pull request merged**
