### PR TITLE
Bump minor version for feature release

### PR DESCRIPTION
**Pull request by cjhowe**
Several features were just merged from pull requests, so I think we should do a minor release. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/92)

### CODE REVIEW

**Comment by nox** [comment]
AFAIK there were no breaking changes, it should be bumped to 0.2.3.

**Comment by cjhowe** [comment]
Done 👍

**Comment by jdm** [comment]
Published!

**Comment by cjhowe** [comment]
Thanks a lot!

**Pull request merged**
