### PR TITLE
Update uuid dep to 1.x

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is exposed in the public API (if the feature is enabled), I think ... so this is probably a breaking change?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/228)

### CODE REVIEW

**Comment by jdm** [comment]
Yes, this will be breaking.

**Comment by atouchet** [comment]
uuid 0.8 is now out.

**Comment by atouchet** [comment]
The stable uuid 1.0 release is out now.

**Comment by atouchet** [comment]
@waywardmonkeys I still see the commit as bumping it to 0.7. Was there a mixup here?

**Comment by waywardmonkeys** [comment]
@atouchet Whoops, yes. Fixed now.

**Comment by mrobinson** [comment]
This is probably a good moment to merge this because the next version will be a major version bump, necessary for a few other breaking changes (upgrading bitflags among others).

**Review by mrobinson — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
Thanks! We'd almost made it to 6 years!

**Pull request merged**
