### PR TITLE
Remove zero-sized struct warning. #106.

### PR DESCRIPTION
**Pull request by rthomas**
This change will fix the remaining warnings in servo/core-text-rs#62 when it is released and the core-text crate is updated.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/core-foundation-rs/107)

### CODE REVIEW

**Comment by rthomas** [comment]
@jdm fyi.

**Comment by jdm** [comment]
Want to increase the version number in Cargo.toml as well so we can publish after merging the changes?

**Comment by rthomas** [comment]
Ack, will do for `core-graphics` as well.

**Comment by rthomas** [comment]
I've bumped the version number.

**Comment by jdm** [comment]
```
error: use of extern static requires unsafe function or block (error E0133)

   --> src/runloop.rs:128:45

    |

128 |         run_loop.add_timer(&run_loop_timer, kCFRunLoopDefaultMode);

    |                                             ^^^^^^^^^^^^^^^^^^^^^

    |

    = note: #[deny(safe_extern_statics)] on by default

    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!

    = note: for more information, see issue #36247 <https://github.com/rust-lang/rust/issues/36247>

error: aborting due to previous error

error: Could not compile `core-foundation`.
```

Want to fix this too?

**Comment by rthomas** [comment]
Yep, will take a look.

**Comment by rthomas** [comment]
Pushed a commit to the PR that fixes this - as it was in the tests I figured wrapping the invocation in `unsafe` was acceptable.

**Pull request merged**
